import db from "./db";

type SeedGroomer = {
  slug: string;
  business_name: string;
  owner_name: string;
  email: string;
  phone: string;
  website: string;
  gmb_url: string;
  description: string;
  city: string;
  zip: string;
  neighborhoods: string[];
  services: string[];
  service_radius_miles: number;
  years_experience: number;
  rating: number;
  review_count: number;
  featured: number;
};

const groomers: SeedGroomer[] = [
  {
    slug: "raleigh-paws-on-wheels",
    business_name: "Raleigh Paws on Wheels",
    owner_name: "Jenna Cole",
    email: "hello@raleighpawsonwheels.com",
    phone: "(919) 555-0142",
    website: "https://raleighpawsonwheels.com",
    gmb_url: "https://g.page/raleighpawsonwheels",
    description:
      "Full-service mobile grooming van serving North Raleigh and Midtown. Fear-free handling and small-batch, one-dog-at-a-time appointments.",
    city: "Raleigh",
    zip: "27609",
    neighborhoods: ["North Hills", "Midtown", "Five Points"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "De-Shedding Treatment", "Puppy's First Groom"],
    service_radius_miles: 12,
    years_experience: 9,
    rating: 4.9,
    review_count: 187,
    featured: 1,
  },
  {
    slug: "cary-canine-spa-mobile",
    business_name: "Cary Canine Spa Mobile",
    owner_name: "Marcus Webb",
    email: "book@carycaninespa.com",
    phone: "(919) 555-0198",
    website: "https://carycaninespa.com",
    gmb_url: "https://g.page/carycaninespa",
    description:
      "Cary's top-rated mobile grooming spa. Climate-controlled van, hypoallergenic shampoos, and gentle handling for anxious pups.",
    city: "Cary",
    zip: "27511",
    neighborhoods: ["Preston", "MacGregor Downs", "Downtown Cary"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Teeth Brushing", "Senior Dog Grooming"],
    service_radius_miles: 15,
    years_experience: 6,
    rating: 4.8,
    review_count: 142,
    featured: 1,
  },
  {
    slug: "apex-mobile-grooming-co",
    business_name: "Apex Mobile Grooming Co.",
    owner_name: "Dana Lippert",
    email: "info@apexmobilegrooming.com",
    phone: "(919) 555-0117",
    website: "https://apexmobilegrooming.com",
    gmb_url: "https://g.page/apexmobilegrooming",
    description:
      "Locally owned and operated, serving Apex and Holly Springs since 2018. Specializing in de-shedding and double-coated breeds.",
    city: "Apex",
    zip: "27502",
    neighborhoods: ["Beaver Creek", "Downtown Apex", "Salem Village"],
    services: ["Full Groom", "De-Shedding Treatment", "Nail Trim", "Ear Cleaning", "Flea & Tick Treatment"],
    service_radius_miles: 10,
    years_experience: 7,
    rating: 4.7,
    review_count: 96,
    featured: 0,
  },
  {
    slug: "wake-forest-fetch-groomers",
    business_name: "Wake Forest Fetch Groomers",
    owner_name: "Priya Nair",
    email: "hi@fetchgroomers.com",
    phone: "(919) 555-0163",
    website: "https://fetchgroomers.com",
    gmb_url: "https://g.page/fetchgroomers",
    description:
      "Family-run mobile grooming for Wake Forest, Rolesville, and Youngsville. We come to your driveway so your dog never feels the stress of a shop.",
    city: "Wake Forest",
    zip: "27587",
    neighborhoods: ["Heritage", "Downtown Wake Forest", "Stonegate"],
    services: ["Full Groom", "Bath & Brush", "Puppy's First Groom", "Nail Trim"],
    service_radius_miles: 18,
    years_experience: 4,
    rating: 4.6,
    review_count: 58,
    featured: 0,
  },
  {
    slug: "morrisville-mobile-mutts",
    business_name: "Morrisville Mobile Mutts",
    owner_name: "Kevin Truong",
    email: "contact@mobilemutts.com",
    phone: "(919) 555-0175",
    website: "https://mobilemutts.com",
    gmb_url: "https://g.page/mobilemutts",
    description:
      "Serving Morrisville and RTP with same-week appointments. Certified in fear-free grooming techniques for reactive and senior dogs.",
    city: "Morrisville",
    zip: "27560",
    neighborhoods: ["Cedar Fork", "Church Street", "Aviation Park"],
    services: ["Full Groom", "Senior Dog Grooming", "Bath & Brush", "Teeth Brushing", "Ear Cleaning"],
    service_radius_miles: 12,
    years_experience: 5,
    rating: 4.9,
    review_count: 121,
    featured: 1,
  },
  {
    slug: "garner-groom-and-go",
    business_name: "Garner Groom & Go",
    owner_name: "Alicia Ford",
    email: "team@groomandgo.com",
    phone: "(919) 555-0184",
    website: "https://groomandgo.com",
    gmb_url: "https://g.page/groomandgo",
    description: "Affordable, no-frills mobile grooming for Garner and Clayton families on the go.",
    city: "Garner",
    zip: "27529",
    neighborhoods: ["Timber Drive", "Downtown Garner", "Vandora Springs"],
    services: ["Bath & Brush", "Nail Trim", "Full Groom"],
    service_radius_miles: 14,
    years_experience: 3,
    rating: 4.5,
    review_count: 41,
    featured: 0,
  },
  {
    slug: "holly-springs-happy-tails",
    business_name: "Holly Springs Happy Tails Mobile Spa",
    owner_name: "Renee Osei",
    email: "renee@happytailsmobile.com",
    phone: "(919) 555-0129",
    website: "https://happytailsmobile.com",
    gmb_url: "https://g.page/happytailsmobile",
    description:
      "Award-winning mobile spa serving Holly Springs and Fuquay-Varina. Ozone-treated water and organic grooming products.",
    city: "Holly Springs",
    zip: "27540",
    neighborhoods: ["Sunset Ridge", "Downtown Holly Springs", "12 Oaks"],
    services: ["Full Groom", "De-Shedding Treatment", "Cat Grooming", "Nail Trim", "Flea & Tick Treatment"],
    service_radius_miles: 16,
    years_experience: 8,
    rating: 4.9,
    review_count: 163,
    featured: 1,
  },
  {
    slug: "knightdale-k9-mobile-cuts",
    business_name: "Knightdale K9 Mobile Cuts",
    owner_name: "Tyrell Banks",
    email: "book@k9mobilecuts.com",
    phone: "(919) 555-0155",
    website: "https://k9mobilecuts.com",
    gmb_url: "https://g.page/k9mobilecuts",
    description: "Breed-specific styling and mobile grooming for Knightdale, Wendell, and Zebulon.",
    city: "Knightdale",
    zip: "27545",
    neighborhoods: ["Widewaters", "Downtown Knightdale", "Forestville"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Puppy's First Groom"],
    service_radius_miles: 15,
    years_experience: 6,
    rating: 4.6,
    review_count: 73,
    featured: 0,
  },
  {
    slug: "fuquay-varina-bark-avenue",
    business_name: "Bark Avenue Mobile Grooming",
    owner_name: "Sophie Marsh",
    email: "sophie@barkavenuemobile.com",
    phone: "(919) 555-0138",
    website: "https://barkavenuemobile.com",
    gmb_url: "https://g.page/barkavenuemobile",
    description: "Fuquay-Varina's premier mobile grooming van. Specializing in show-cut styling and hand-stripping.",
    city: "Fuquay-Varina",
    zip: "27526",
    neighborhoods: ["Downtown Fuquay-Varina", "Ashford", "Weston"],
    services: ["Full Groom", "De-Shedding Treatment", "Senior Dog Grooming", "Teeth Brushing"],
    service_radius_miles: 13,
    years_experience: 10,
    rating: 5.0,
    review_count: 209,
    featured: 1,
  },
  {
    slug: "north-raleigh-shear-comfort",
    business_name: "Shear Comfort Mobile Grooming",
    owner_name: "Latoya Simmons",
    email: "info@shearcomfortmobile.com",
    phone: "(919) 555-0111",
    website: "https://shearcomfortmobile.com",
    gmb_url: "https://g.page/shearcomfortmobile",
    description: "Gentle, patient grooming for anxious and senior dogs in North Raleigh and Wakefield.",
    city: "Raleigh",
    zip: "27614",
    neighborhoods: ["Wakefield", "Bedford", "North Raleigh"],
    services: ["Senior Dog Grooming", "Bath & Brush", "Nail Trim", "Ear Cleaning"],
    service_radius_miles: 14,
    review_count: 89,
    years_experience: 12,
    rating: 4.8,
    featured: 0,
  },
  {
    slug: "downtown-raleigh-tailwaggers",
    business_name: "Downtown Tailwaggers Mobile",
    owner_name: "Chris Halloran",
    email: "chris@tailwaggersmobile.com",
    phone: "(919) 555-0199",
    website: "https://tailwaggersmobile.com",
    gmb_url: "https://g.page/tailwaggersmobile",
    description: "Serving downtown condos and townhomes in Oakwood, Boylan Heights, and Glenwood South.",
    city: "Raleigh",
    zip: "27601",
    neighborhoods: ["Oakwood", "Boylan Heights", "Glenwood South"],
    services: ["Bath & Brush", "Full Groom", "Nail Trim", "Cat Grooming"],
    service_radius_miles: 8,
    years_experience: 5,
    rating: 4.7,
    review_count: 67,
    featured: 0,
  },
  {
    slug: "brier-creek-pupmobile",
    business_name: "Brier Creek Pupmobile",
    owner_name: "Ana Reyes",
    email: "hello@pupmobilenc.com",
    phone: "(919) 555-0166",
    website: "https://pupmobilenc.com",
    gmb_url: "https://g.page/pupmobilenc",
    description: "Convenient at-home grooming for Brier Creek and Northwest Raleigh, near RDU.",
    city: "Raleigh",
    zip: "27617",
    neighborhoods: ["Brier Creek", "Stonehenge", "Bent Tree"],
    services: ["Full Groom", "Puppy's First Groom", "Bath & Brush", "Flea & Tick Treatment"],
    service_radius_miles: 11,
    years_experience: 4,
    rating: 4.6,
    review_count: 52,
    featured: 0,
  },
  {
    slug: "zebulon-zoomies-mobile-groom",
    business_name: "Zoomies Mobile Grooming",
    owner_name: "Whitney Farr",
    email: "whitney@zoomiesmobile.com",
    phone: "(919) 555-0122",
    website: "https://zoomiesmobile.com",
    gmb_url: "https://g.page/zoomiesmobile",
    description: "Eastern Wake County's friendliest mobile groomers, serving Zebulon, Wendell, and Bunn.",
    city: "Zebulon",
    zip: "27597",
    neighborhoods: ["Downtown Zebulon", "Mill Creek"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim"],
    service_radius_miles: 20,
    years_experience: 2,
    rating: 4.4,
    review_count: 23,
    featured: 0,
  },
  {
    slug: "cameron-village-clip-joint",
    business_name: "Cameron Village Clip Joint Mobile",
    owner_name: "Ben Osei",
    email: "ben@clipjointmobile.com",
    phone: "(919) 555-0147",
    website: "https://clipjointmobile.com",
    gmb_url: "https://g.page/clipjointmobile",
    description: "Boutique mobile grooming for small breeds and cats near Cameron Village and NC State.",
    city: "Raleigh",
    zip: "27607",
    neighborhoods: ["Cameron Village", "Hayes Barton", "Cameron Park"],
    services: ["Full Groom", "Cat Grooming", "Nail Trim", "Teeth Brushing"],
    service_radius_miles: 9,
    years_experience: 6,
    rating: 4.8,
    review_count: 104,
    featured: 0,
  },
  {
    slug: "west-cary-suds-n-scruff",
    business_name: "Suds N' Scruff Mobile",
    owner_name: "Hannah Diaz",
    email: "hannah@sudsnscruff.com",
    phone: "(919) 555-0188",
    website: "https://sudsnscruff.com",
    gmb_url: "https://g.page/sudsnscruff",
    description: "West Cary and Morrisville's go-to for de-shedding treatments and double-coat breeds.",
    city: "Cary",
    zip: "27519",
    neighborhoods: ["Amberly", "Highcroft", "West Cary"],
    services: ["De-Shedding Treatment", "Full Groom", "Bath & Brush", "Ear Cleaning"],
    service_radius_miles: 12,
    years_experience: 7,
    rating: 4.7,
    review_count: 88,
    featured: 0,
  },
  {
    slug: "durham-bull-city-pawspa",
    business_name: "Bull City Paw Spa Mobile",
    owner_name: "Marcus Ellison",
    email: "hello@bullcitypawspa.com",
    phone: "(919) 555-0212",
    website: "https://bullcitypawspa.com",
    gmb_url: "https://g.page/bullcitypawspa",
    description:
      "Durham's original mobile grooming spa, serving downtown lofts and Duke-area neighborhoods since 2016. Fear-free certified.",
    city: "Durham",
    zip: "27701",
    neighborhoods: ["Downtown Durham", "Trinity Park", "Duke Park"],
    services: ["Full Groom", "Bath & Brush", "De-Shedding Treatment", "Nail Trim", "Cat Grooming"],
    service_radius_miles: 14,
    years_experience: 9,
    rating: 4.9,
    review_count: 176,
    featured: 1,
  },
  {
    slug: "durham-southpoint-mobile-groom",
    business_name: "Southpoint Mobile Grooming",
    owner_name: "Deja Watts",
    email: "book@southpointmobile.com",
    phone: "(919) 555-0223",
    website: "https://southpointmobile.com",
    gmb_url: "https://g.page/southpointmobile",
    description: "Serving South Durham and RTP with flexible weekend and evening appointments.",
    city: "Durham",
    zip: "27713",
    neighborhoods: ["Southpoint", "Woodcroft", "Research Triangle Park"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Puppy's First Groom"],
    service_radius_miles: 15,
    years_experience: 5,
    rating: 4.6,
    review_count: 64,
    featured: 0,
  },
  {
    slug: "chapel-hill-tarheel-tails",
    business_name: "Tar Heel Tails Mobile Grooming",
    owner_name: "Sarah Kim",
    email: "sarah@tarheeltails.com",
    phone: "(919) 555-0234",
    website: "https://tarheeltails.com",
    gmb_url: "https://g.page/tarheeltails",
    description:
      "Chapel Hill and Carrboro's favorite mobile groomer, known for gentle handling of senior and rescue dogs.",
    city: "Chapel Hill",
    zip: "27514",
    neighborhoods: ["Downtown Chapel Hill", "Southern Village", "Meadowmont"],
    services: ["Full Groom", "Senior Dog Grooming", "Bath & Brush", "Teeth Brushing", "Ear Cleaning"],
    service_radius_miles: 13,
    years_experience: 11,
    rating: 5.0,
    review_count: 198,
    featured: 1,
  },
  {
    slug: "carrboro-mobile-mutt-cuts",
    business_name: "Carrboro Mutt Cuts Mobile",
    owner_name: "Owen Fischer",
    email: "owen@muttcutsmobile.com",
    phone: "(919) 555-0245",
    website: "https://muttcutsmobile.com",
    gmb_url: "https://g.page/muttcutsmobile",
    description: "Locally owned, eco-friendly mobile grooming serving Carrboro and West Chapel Hill.",
    city: "Carrboro",
    zip: "27510",
    neighborhoods: ["Downtown Carrboro", "Carr Mill"],
    services: ["Full Groom", "Bath & Brush", "De-Shedding Treatment", "Nail Trim"],
    service_radius_miles: 10,
    years_experience: 4,
    rating: 4.7,
    review_count: 47,
    featured: 0,
  },
  {
    slug: "hillsborough-heritage-hounds",
    business_name: "Heritage Hounds Mobile Grooming",
    owner_name: "Callie Norwood",
    email: "callie@heritagehounds.com",
    phone: "(919) 555-0256",
    website: "https://heritagehounds.com",
    gmb_url: "https://g.page/heritagehounds",
    description: "Serving historic Hillsborough and the rural stretches of Orange County.",
    city: "Hillsborough",
    zip: "27278",
    neighborhoods: ["Downtown Hillsborough", "Waterstone"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Flea & Tick Treatment"],
    service_radius_miles: 20,
    years_experience: 6,
    rating: 4.6,
    review_count: 38,
    featured: 0,
  },
  {
    slug: "burlington-alamance-paws",
    business_name: "Alamance Paws Mobile Grooming",
    owner_name: "Rick Dalton",
    email: "rick@alamancepaws.com",
    phone: "(336) 555-0167",
    website: "https://alamancepaws.com",
    gmb_url: "https://g.page/alamancepaws",
    description: "Burlington and Graham's trusted mobile groomer, halfway between Durham and Greensboro.",
    city: "Burlington",
    zip: "27215",
    neighborhoods: ["Downtown Burlington", "Alamance Crossing"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Senior Dog Grooming"],
    service_radius_miles: 18,
    years_experience: 8,
    rating: 4.7,
    review_count: 71,
    featured: 0,
  },
  {
    slug: "greensboro-gate-city-groom-mobile",
    business_name: "Gate City Mobile Grooming",
    owner_name: "Tanya Brooks",
    email: "tanya@gatecitymobile.com",
    phone: "(336) 555-0178",
    website: "https://gatecitymobile.com",
    gmb_url: "https://g.page/gatecitymobile",
    description:
      "Greensboro's top-rated mobile grooming van, serving Fisher Park to Irving Park with award-winning customer service.",
    city: "Greensboro",
    zip: "27401",
    neighborhoods: ["Fisher Park", "Irving Park", "Downtown Greensboro"],
    services: ["Full Groom", "Bath & Brush", "De-Shedding Treatment", "Cat Grooming", "Teeth Brushing"],
    service_radius_miles: 16,
    years_experience: 10,
    rating: 4.9,
    review_count: 154,
    featured: 1,
  },
  {
    slug: "greensboro-triad-tail-waggers",
    business_name: "Triad Tail Waggers Mobile",
    owner_name: "Jordan Pace",
    email: "jordan@triadtailwaggers.com",
    phone: "(336) 555-0189",
    website: "https://triadtailwaggers.com",
    gmb_url: "https://g.page/triadtailwaggers",
    description: "Serving Greensboro's north side and Summerfield with same-week booking.",
    city: "Greensboro",
    zip: "27410",
    neighborhoods: ["Lake Jeanette", "Northwood Estates"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Puppy's First Groom"],
    service_radius_miles: 15,
    years_experience: 3,
    rating: 4.5,
    review_count: 29,
    featured: 0,
  },
  {
    slug: "high-point-furniture-city-fluff",
    business_name: "Furniture City Fluff & Groom",
    owner_name: "Erica Holloway",
    email: "erica@furniturecityfluff.com",
    phone: "(336) 555-0191",
    website: "https://furniturecityfluff.com",
    gmb_url: "https://g.page/furniturecityfluff",
    description: "High Point's only dedicated mobile groomer, specializing in show-quality breed cuts.",
    city: "High Point",
    zip: "27262",
    neighborhoods: ["Emerywood", "Oak Hollow"],
    services: ["Full Groom", "De-Shedding Treatment", "Senior Dog Grooming", "Ear Cleaning"],
    service_radius_miles: 14,
    years_experience: 7,
    rating: 4.8,
    review_count: 82,
    featured: 0,
  },
  {
    slug: "youngsville-north-wake-mobile-groom",
    business_name: "North Wake Mobile Grooming",
    owner_name: "Katie Sasser",
    email: "katie@northwakemobile.com",
    phone: "(919) 555-0267",
    website: "https://northwakemobile.com",
    gmb_url: "https://g.page/northwakemobile",
    description: "Serving Youngsville, Franklinton, and the far north Wake County line.",
    city: "Youngsville",
    zip: "27596",
    neighborhoods: ["Downtown Youngsville", "Points at Wakefield"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim"],
    service_radius_miles: 18,
    years_experience: 3,
    rating: 4.5,
    review_count: 19,
    featured: 0,
  },
  {
    slug: "clayton-johnston-county-mobile-groom",
    business_name: "Johnston County Mobile Grooming",
    owner_name: "Brandon Lucas",
    email: "brandon@johnstoncountymobile.com",
    phone: "(919) 555-0278",
    website: "https://johnstoncountymobile.com",
    gmb_url: "https://g.page/johnstoncountymobile",
    description: "Clayton's hometown mobile groomer, also serving Smithfield and Selma.",
    city: "Clayton",
    zip: "27520",
    neighborhoods: ["Downtown Clayton", "Flowers Plantation"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Puppy's First Groom"],
    service_radius_miles: 20,
    years_experience: 6,
    rating: 4.7,
    review_count: 54,
    featured: 0,
  },
  {
    slug: "smithfield-neuse-river-mobile-groom",
    business_name: "Neuse River Mobile Grooming",
    owner_name: "Angela Creech",
    email: "angela@neuserivermobile.com",
    phone: "(919) 555-0289",
    website: "https://neuserivermobile.com",
    gmb_url: "https://g.page/neuserivermobile",
    description: "Family-owned mobile grooming serving Smithfield, Selma, and Four Oaks.",
    city: "Smithfield",
    zip: "27577",
    neighborhoods: ["Downtown Smithfield", "River Ridge"],
    services: ["Full Groom", "Bath & Brush", "De-Shedding Treatment", "Senior Dog Grooming"],
    service_radius_miles: 16,
    years_experience: 9,
    rating: 4.8,
    review_count: 67,
    featured: 0,
  },
  {
    slug: "angier-harnett-line-mobile-groom",
    business_name: "Harnett Line Mobile Grooming",
    owner_name: "Terry Adcock",
    email: "terry@harnettlinemobile.com",
    phone: "(919) 555-0291",
    website: "https://harnettlinemobile.com",
    gmb_url: "https://g.page/harnettlinemobile",
    description: "Serving Angier, Lillington, and southern Wake County.",
    city: "Angier",
    zip: "27501",
    neighborhoods: ["Downtown Angier"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Flea & Tick Treatment"],
    service_radius_miles: 17,
    years_experience: 4,
    rating: 4.6,
    review_count: 26,
    featured: 0,
  },
  {
    slug: "pittsboro-chatham-county-mobile-groom",
    business_name: "Chatham County Mobile Grooming",
    owner_name: "Renee Sykes",
    email: "renee@chathamcountymobile.com",
    phone: "(919) 555-0304",
    website: "https://chathamcountymobile.com",
    gmb_url: "https://g.page/chathamcountymobile",
    description: "Pittsboro and Siler City's only mobile groomer, serving rural Chatham County properties.",
    city: "Pittsboro",
    zip: "27312",
    neighborhoods: ["Downtown Pittsboro", "Chatham Park"],
    services: ["Full Groom", "Bath & Brush", "De-Shedding Treatment", "Nail Trim"],
    service_radius_miles: 22,
    years_experience: 5,
    rating: 4.7,
    review_count: 33,
    featured: 0,
  },
  {
    slug: "oxford-granville-county-mobile-groom",
    business_name: "Granville County Mobile Grooming",
    owner_name: "Denise Currin",
    email: "denise@granvillecountymobile.com",
    phone: "(919) 555-0315",
    website: "https://granvillecountymobile.com",
    gmb_url: "https://g.page/granvillecountymobile",
    description: "Serving Oxford, Butner, and the far north Triangle.",
    city: "Oxford",
    zip: "27565",
    neighborhoods: ["Downtown Oxford"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim"],
    service_radius_miles: 20,
    years_experience: 2,
    rating: 4.4,
    review_count: 14,
    featured: 0,
  },
];

function run() {
  const existing = db.prepare("SELECT COUNT(*) as c FROM groomers").get() as { c: number };
  if (existing.c > 0) {
    console.log(`Database already has ${existing.c} rows. Skipping seed.`);
    return;
  }

  const insert = db.prepare(`
    INSERT INTO groomers (
      slug, business_name, owner_name, email, phone, website, gmb_url, description,
      city, zip, neighborhoods, services, service_radius_miles, years_experience,
      rating, review_count, featured, status
    ) VALUES (
      @slug, @business_name, @owner_name, @email, @phone, @website, @gmb_url, @description,
      @city, @zip, @neighborhoods, @services, @service_radius_miles, @years_experience,
      @rating, @review_count, @featured, 'approved'
    )
  `);

  const insertMany = db.transaction((rows: SeedGroomer[]) => {
    for (const row of rows) {
      insert.run({
        ...row,
        neighborhoods: JSON.stringify(row.neighborhoods),
        services: JSON.stringify(row.services),
      });
    }
  });

  insertMany(groomers);
  console.log(`Seeded ${groomers.length} groomers.`);
}

run();
