// Real mobile dog groomers found via web search (Sept 2026), not fabricated
// businesses. Ratings/review counts default to 0 (unverified) and only get a
// real value when a specific "X stars from Y reviews" pairing was found from
// a credible source — never guessed from vague marketing copy. gmb_url is a
// Google Maps *search* link (not a claimed/confirmed Google Business
// Profile) since we haven't verified an exact listing for each. All rows
// start unclaimed (is_claimed=0); owners can claim via /groomer/[slug]/claim.
import { sql, ensureSchema } from "./db";

function mapsSearchUrl(businessName: string, city: string): string {
  const q = `${businessName} ${city} NC`;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
}

type SeedGroomer = {
  slug: string;
  business_name: string;
  owner_name?: string | null;
  phone?: string | null;
  website?: string | null;
  facebook_url?: string | null;
  // Freeform, only set when a source (website, Facebook, Yelp Q&A, etc.)
  // states real prices — never estimated or inferred from "affordable"-type
  // marketing language.
  price_info?: string | null;
  hours?: string | null;
  service_radius_miles?: number;
  description: string;
  city: string;
  zip: string;
  neighborhoods: string[];
  services: string[];
  years_experience?: number | null;
  // Only set when a specific rating+review-count pair was found together
  // from a credible source (e.g. "4.8 stars based on 36 reviews") — never
  // guessed or inferred from vague marketing copy like "thousands of happy
  // customers." Leave both unset (0/0) when unconfirmed; the UI shows
  // "New listing" rather than a fake 0.0.
  rating?: number;
  review_count?: number;
};

const groomers: SeedGroomer[] = [
  {
    slug: "raleigh-lucky-dog-mobile-groomers",
    business_name: "Lucky Dog Mobile Groomers",
    phone: "(919) 867-0000",
    website: "https://www.luckydogmobilegroomers.com/raleigh-nc/",
    description:
      "Mobile dog grooming serving Raleigh, Cary, Apex, Morrisville, Wake Forest, Holly Springs, Garner, and Knightdale. Cage-free, one-on-one appointments in your driveway.",
    city: "Raleigh",
    zip: "27609",
    neighborhoods: ["Raleigh", "Cary", "Apex", "Morrisville", "Wake Forest", "Holly Springs", "Garner", "Knightdale"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Ear Cleaning"],
    rating: 5.0,
    review_count: 81,
  },
  {
    slug: "raleigh-brandyapple-grooming",
    business_name: "Brandyapple Grooming",
    website: "https://www.brandyapplegrooming.com/",
    description:
      "Mobile pet grooming in Raleigh offering haircuts, baths, deshedding, and nail trims delivered to your doorstep.",
    city: "Raleigh",
    zip: "27609",
    neighborhoods: ["Raleigh"],
    services: ["Full Groom", "Bath & Brush", "De-Shedding Treatment", "Nail Trim"],
    rating: 5.0,
    review_count: 22,
  },
  {
    slug: "raleigh-sparklin-petz-mobile-grooming",
    business_name: "Sparklin' Petz Mobile Grooming Spa",
    phone: "919-721-2319",
    website: "https://www.sparklinpetzgrooming.com/",
    description: "Mobile pet grooming based at 5123 Obion Ct, Raleigh, NC.",
    city: "Raleigh",
    zip: "27616",
    neighborhoods: ["Raleigh"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.4,
    review_count: 14,
  },
  {
    slug: "raleigh-grooming-by-greicis",
    business_name: "Grooming by Greicis",
    phone: "(984) 389-9030",
    website: "https://www.groomingbygreicis.com/",
    description:
      "Mobile pet grooming serving the Eastern Wake area, including Raleigh, Wendell, Knightdale, Wake Forest, Garner, Clayton, and Holly Springs.",
    city: "Raleigh",
    zip: "27610",
    neighborhoods: ["Raleigh", "Wendell", "Knightdale", "Wake Forest", "Garner", "Clayton", "Holly Springs"],
    services: ["Full Groom", "Bath & Brush"],
    price_info: "Full-service grooming starts at $85, with final pricing based on breed and size.",
    rating: 4.9,
    review_count: 30,
  },
  {
    slug: "raleigh-canis-major-mobile-pet-spa",
    business_name: "Canis Major Mobile Pet Spa",
    phone: "919-475-8055",
    website: "https://www.canismajorpetspa.com/",
    description: "Full-service mobile grooming salon serving Raleigh, Garner, and surrounding areas.",
    city: "Raleigh",
    zip: "27603",
    neighborhoods: ["Raleigh", "Garner"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 3,
  },
  {
    slug: "raleigh-all-fur-pets-grooming",
    business_name: "All Fur Pets Dog and Cat Grooming",
    phone: "919-729-4838",
    description: "Mobile dog and cat grooming in Raleigh, NC with 20+ years of experience.",
    city: "Raleigh",
    zip: "27612",
    neighborhoods: ["Raleigh"],
    services: ["Full Groom", "Bath & Brush", "Cat Grooming"],
    rating: 4.4,
    review_count: 19,
    years_experience: 20,
  },
  {
    slug: "raleigh-rub-a-dub-doggie",
    business_name: "Rub A Dub Doggie",
    phone: "(919) 847-1199",
    website: "http://www.raddoggie.com",
    description: "Mobile dog grooming based at 10513 Whitestone Rd, Raleigh, NC, established 2007.",
    city: "Raleigh",
    zip: "27615",
    neighborhoods: ["Raleigh"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.0,
    review_count: 9,
  },
  {
    slug: "raleigh-indigo-spaw-mobile-grooming",
    business_name: "Indigo Spaw Mobile Grooming",
    phone: "(919) 830-6504",
    description: "Mobile dog grooming based at 6300 Limousine Dr, Raleigh, NC, serving Raleigh, Morrisville, and Cary.",
    city: "Raleigh",
    zip: "27617",
    neighborhoods: ["Raleigh", "Morrisville", "Cary"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 2.5,
    review_count: 11,
    hours: "Mon-Sat 8:30am-4:00pm",
  },
  {
    slug: "raleigh-hydrodog-north-raleigh",
    business_name: "HydroDog - North Raleigh",
    website: "https://hydrodog.com/",
    description: "Mobile dog grooming serving North Raleigh, part of the national HydroDog franchise network.",
    city: "Raleigh",
    zip: "27614",
    neighborhoods: ["Raleigh"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 1,
  },
  {
    slug: "cary-the-pooch-mobile",
    business_name: "The Pooch Mobile",
    phone: "(919) 410-6060",
    description:
      "Mobile dog grooming in Cary offering warm hydrobaths with all-natural products, a full blow dry, brushing, nail trimming, and ear/eye cleaning.",
    city: "Cary",
    zip: "27511",
    neighborhoods: ["Cary"],
    services: ["Bath & Brush", "Nail Trim", "Ear Cleaning"],
    rating: 5.0,
    review_count: 6,
  },
  {
    slug: "apex-exquisite-paws",
    business_name: "Exquisite Paws Mobile Dog Grooming",
    phone: "(321) 614-1427",
    description: "Mobile dog grooming in Apex, coming to your home for a convenient, stress-free grooming experience.",
    city: "Apex",
    zip: "27502",
    neighborhoods: ["Apex"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 5,
  },
  {
    slug: "durham-soapy-paws",
    business_name: "Soapy Paws Mobile Pet Grooming",
    phone: "(919) 451-8416",
    website: "https://soapypawsmobilepetgrooming.com/",
    description:
      "Mobile pet grooming servicing Raleigh, Apex, Cary, Durham, Morrisville, Holly Springs, Chapel Hill, and Fuquay-Varina.",
    city: "Durham",
    zip: "27701",
    neighborhoods: ["Durham", "Raleigh", "Apex", "Cary", "Morrisville", "Holly Springs", "Chapel Hill", "Fuquay-Varina"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 13,
  },
  {
    slug: "durham-adore-pet-spa",
    business_name: "Adore Pet Spa",
    phone: "(919) 667-7688",
    website: "https://adorepetspa.com/",
    description: "Mobile dog grooming serving Durham and Chapel Hill, NC with expert services right at your doorstep.",
    city: "Durham",
    zip: "27713",
    neighborhoods: ["Durham", "Chapel Hill"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.7,
    review_count: 13,
  },
  {
    slug: "durham-fashion-pets-mobile",
    business_name: "Fashion Pets Mobile",
    phone: "(984) 319-9332",
    website: "https://fashionpetsmobile.com/",
    description: "Mobile pet grooming based at 2829 N Roxboro St, Durham, NC, with pickup and delivery options.",
    city: "Durham",
    zip: "27704",
    neighborhoods: ["Durham"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.8,
    review_count: 23,
  },
  {
    slug: "durham-roaming-rovers",
    business_name: "Roaming Rovers",
    phone: "919-704-0251",
    website: "https://roamingroversnc.com/",
    description: "Family-owned luxury mobile pet grooming based in Durham, NC.",
    city: "Durham",
    zip: "27713",
    neighborhoods: ["Durham"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 137,
  },
  {
    slug: "chapel-hill-canine-refinery",
    business_name: "Canine Refinery Mobile Grooming",
    website: "https://www.facebook.com/p/Canine-Refinery-Mobile-Grooming-100076594340798/",
    description: "Mobile dog grooming serving the Chapel Hill, NC area.",
    city: "Chapel Hill",
    zip: "27514",
    neighborhoods: ["Chapel Hill"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "wake-forest-splash-mobile-pet-salon",
    business_name: "Splash Mobile Pet Salon",
    phone: "(919) 880-1117",
    description: "Mobile pet grooming salon based in Wake Forest, NC.",
    city: "Wake Forest",
    zip: "27587",
    neighborhoods: ["Wake Forest"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 1,
  },
  {
    slug: "wake-forest-classy-k9-mobile-grooming",
    business_name: "Classy K9 Mobile Grooming",
    phone: "(919) 637-9412",
    website: "https://www.classyk9mobilegrooming.com/",
    description:
      "Mobile dog grooming servicing Wake Forest, North Raleigh, North Durham, Youngsville, Rolesville, Franklinton, Creedmoor, and Henderson.",
    city: "Wake Forest",
    zip: "27587",
    neighborhoods: ["Wake Forest", "North Raleigh", "North Durham", "Youngsville", "Rolesville", "Franklinton"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 106,
  },
  {
    slug: "smithfield-k9-clips-pet-grooming",
    business_name: "K9 Clips Pet Grooming",
    phone: "(919) 938-2777",
    website: "https://www.k9clips.net/",
    description:
      "Mobile pet grooming based at 6376 NC Hwy 210, Smithfield, serving Johnston County and surrounding areas including Garner and Clayton. Google lists this business as temporarily closed. Confirm availability before booking.",
    city: "Smithfield",
    zip: "27577",
    neighborhoods: ["Smithfield", "Garner", "Clayton"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim"],
    years_experience: 22,
    rating: 5.0,
    review_count: 4,
  },
  {
    slug: "holly-springs-whiskers-and-tails",
    business_name: "Whiskers & Tails Mobile Dog Grooming",
    phone: "(919) 306-6363",
    website: "https://whiskersandtailsnc.com/",
    description:
      "Mobile dog grooming at your doorstep serving Holly Springs, Fuquay-Varina, Garner, Apex, Cary, Willow Springs, and Angier.",
    city: "Holly Springs",
    zip: "27540",
    neighborhoods: ["Holly Springs", "Fuquay-Varina", "Garner", "Apex", "Cary", "Angier"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.8,
    review_count: 36,
  },
  {
    slug: "fuquay-varina-top-dog-pet-services",
    business_name: "Top Dog Pet Services",
    phone: "(919) 267-5130",
    website: "https://topdogpetservices.com/",
    description: "Professional mobile pet grooming at your doorstep serving Holly Springs, Apex, Cary, Fuquay-Varina, and Raleigh.",
    city: "Fuquay-Varina",
    zip: "27526",
    neighborhoods: ["Fuquay-Varina", "Holly Springs", "Apex", "Cary", "Raleigh"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.8,
    review_count: 122,
  },
  {
    slug: "morrisville-woofies",
    business_name: "Woofie's of Northwest Raleigh-Cary",
    phone: "(984) 377-5080",
    website: "https://www.woofies.com/northwest-raleigh-cary/morrisville/mobile-pet-grooming/",
    description: "Mobile pet grooming in Morrisville tailored to your dog's breed, coat type, and household routine.",
    city: "Morrisville",
    zip: "27560",
    neighborhoods: ["Morrisville"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 151,
  },
  {
    slug: "knightdale-furry-land",
    business_name: "Furry Land Mobile Grooming",
    phone: "(919) 766-9339",
    website: "https://furryland.us/dog-grooming-knightdale-nc/",
    description: "Mobile pet grooming serving Knightdale, NC and the greater Raleigh-Durham area.",
    city: "Knightdale",
    zip: "27545",
    neighborhoods: ["Knightdale"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.9,
    review_count: 229,
  },
  {
    slug: "knightdale-pup-pup-dog-grooming",
    business_name: "Pup Pup Dog Grooming",
    phone: "(919) 741-3941",
    description: "Mobile dog grooming based in Knightdale, serving Knightdale, Raleigh, Durham, and Wendell.",
    city: "Knightdale",
    zip: "27545",
    neighborhoods: ["Knightdale", "Raleigh", "Durham", "Wendell"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "zebulon-carolina-mobile-spaw",
    business_name: "Carolina Mobile Spaw",
    phone: "(919) 274-4470",
    website: "https://carolinamobilespaw.com/",
    description:
      "Mobile dog grooming with 15 years of experience, servicing select areas of Raleigh, Wendell, Knightdale, Rolesville, Zebulon, Archer Lodge, Wake Forest, and Youngsville.",
    city: "Zebulon",
    zip: "27597",
    neighborhoods: ["Zebulon", "Wendell", "Knightdale", "Rolesville", "Wake Forest", "Youngsville"],
    services: ["Full Groom", "Bath & Brush"],
    years_experience: 15,
    rating: 5.0,
    review_count: 2,
  },
  {
    slug: "zebulon-puppy-pawlor-mobile-grooming",
    business_name: "Puppy Pawlor Mobile Grooming",
    phone: "(919) 600-4277",
    website: "https://puppypawlorgrooming.com/",
    description:
      "Mobile dog grooming based at 2876 Pilot-Riley Rd, Zebulon, NC, serving the Research Triangle area. Yelp lists this business as temporarily closed. Confirm availability before booking.",
    city: "Zebulon",
    zip: "27597",
    neighborhoods: ["Zebulon"],
    services: ["Full Groom", "Bath & Brush"],
    hours: "Mon-Fri 8:00am-6:00pm",
    rating: 5.0,
    review_count: 3,
  },
  {
    slug: "wendell-charmed-pet-grooming",
    business_name: "Charmed Pet Grooming",
    phone: "(919) 348-7564",
    website: "https://www.charmedpetgrooming.com/",
    description: "Mobile pet grooming serving Wendell, Knightdale, and Zebulon with over 10 years of grooming experience.",
    city: "Wendell",
    zip: "27591",
    neighborhoods: ["Wendell", "Knightdale", "Zebulon"],
    services: ["Full Groom", "Bath & Brush"],
    years_experience: 10,
    rating: 4.5,
    review_count: 8,
  },
  {
    slug: "rolesville-pampered-pups",
    business_name: "Pampered Pups Mobile Grooming",
    phone: "(919) 671-3657",
    website: "https://pamperedpupsmobilegrooming.com/",
    description: "Mobile grooming serving Raleigh, Wake Forest, Rolesville, and Youngsville.",
    city: "Rolesville",
    zip: "27571",
    neighborhoods: ["Rolesville", "Raleigh", "Wake Forest", "Youngsville"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 34,
  },
  {
    slug: "smithfield-paws-n-claws-grooming",
    business_name: "Paws N Claws Grooming",
    website: "https://www.pawsnclawsgrooming.net/",
    description: "Pet grooming based at 1317 N Brightleaf Blvd, Smithfield, serving Smithfield and Clayton, NC.",
    city: "Smithfield",
    zip: "27577",
    neighborhoods: ["Smithfield", "Clayton"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.4,
    review_count: 27,
  },
  {
    slug: "greensboro-dappertails",
    business_name: "DapperTails Mobile Pet Grooming",
    phone: "(336) 805-6444",
    website: "https://www.dappertailsmobile.com/greensboro-nc",
    description:
      "Mobile pet grooming bringing the salon directly to your home, with baths, breed-specific haircuts, nail trims, and deshedding for dogs throughout Greensboro.",
    city: "Greensboro",
    zip: "27401",
    neighborhoods: ["Greensboro"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "De-Shedding Treatment"],
    rating: 4.9,
    review_count: 114,
  },
  {
    slug: "greensboro-pretty-dog-clean",
    business_name: "Pretty Dog Clean",
    phone: "(336) 964-7141",
    website: "https://www.prettydogclean.com/",
    owner_name: "Kiana Smith",
    description: "Mobile grooming business servicing local pets of every breed for all grooming needs in Greensboro, North Carolina.",
    city: "Greensboro",
    zip: "27410",
    neighborhoods: ["Greensboro"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.7,
    review_count: 17,
  },
  {
    slug: "high-point-scooby-dos",
    business_name: "Scooby Dos Mobile Pet Grooming",
    phone: "(336) 423-6344",
    description: "Mobile pet grooming located at 217 W Lexington Ave, High Point, NC.",
    city: "High Point",
    zip: "27262",
    neighborhoods: ["High Point"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "burlington-for-the-love-of-dogs",
    business_name: "For the Love Of Dogs Mobile Grooming",
    phone: "(336) 213-5060",
    description: "Mobile dog grooming based in Burlington, NC.",
    city: "Burlington",
    zip: "27215",
    neighborhoods: ["Burlington"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "burlington-scissors-and-suds",
    business_name: "Scissors & Suds Mobile Dog Grooming",
    description: "Mobile dog grooming serving Burlington, NC.",
    city: "Burlington",
    zip: "27216",
    neighborhoods: ["Burlington"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "chapel-hill-awbreys-ark",
    business_name: "Awbreys Ark Mobile Pet Spa",
    phone: "(919) 292-7397",
    website: "https://awbreysark.com/",
    description: "Mobile pet spa offering dog grooming and pet massage serving the Chapel Hill, Carrboro, and Hillsborough area.",
    city: "Chapel Hill",
    zip: "27514",
    neighborhoods: ["Chapel Hill", "Carrboro", "Hillsborough"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.6,
    review_count: 8,
  },
  {
    slug: "siler-city-pampered-paws",
    business_name: "Pampered Paws Dog Grooming LLC",
    website: "https://www.facebook.com/p/Pampered-Paws-Dog-Grooming-LLC-100088334014270/",
    description: "Mobile dog grooming based in Siler City, NC.",
    city: "Siler City",
    zip: "27344",
    neighborhoods: ["Siler City"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "pittsboro-darlas-little-rascals",
    business_name: "Darla's Little Rascals Mobile Pet Grooming, LLC",
    phone: "(919) 548-0110",
    description: "Mobile dog grooming based in Pittsboro, NC. Darla has been a mobile groomer for over 30 years.",
    city: "Pittsboro",
    zip: "27312",
    neighborhoods: ["Pittsboro"],
    services: ["Full Groom", "Bath & Brush"],
    hours: "Mon 10:00am-5:00pm, Tue-Fri 9:00am-5:00pm",
    years_experience: 30,
    rating: 4.1,
    review_count: 9,
  },
  {
    slug: "lillington-mutt-kuttz",
    business_name: "Mutt Kuttz Doggie Spa",
    phone: "(910) 242-6464",
    description: "Professional one-on-one dog grooming from a certified, licensed, insured pet stylist, based at 1026 South Main St, Lillington, NC, also serving Angier.",
    city: "Lillington",
    zip: "27546",
    neighborhoods: ["Lillington", "Angier"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.6,
    review_count: 10,
  },
  {
    slug: "lillington-kr-groovin-grooming",
    business_name: "KR Groovin' Grooming LLC",
    phone: "(919) 396-2740",
    website: "https://www.facebook.com/KRGroovinGrooming/",
    description: "Local mobile dog grooming serving Harnett, Johnston, and Southern Wake County.",
    city: "Lillington",
    zip: "27546",
    neighborhoods: ["Lillington"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 20,
  },
  {
    slug: "youngsville-morgan-mobile-grooming",
    business_name: "Morgan Mobile Grooming",
    phone: "(919) 671-0142",
    website: "http://www.morganmobilegrooming.com/",
    description:
      "Mobile pet grooming in Youngsville offering bathing, haircuts, ear cleaning, and nail trimming, with add-ons like paw treatments and teeth cleaning.",
    city: "Youngsville",
    zip: "27596",
    neighborhoods: ["Youngsville"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "Ear Cleaning", "Teeth Brushing"],
    rating: 5.0,
    review_count: 4,
  },
  {
    slug: "raleigh-zoomin-groomin",
    business_name: "Zoomin Groomin",
    phone: "(984) 500-0803",
    website: "https://www.zoomingroomin.com/locations/north-carolina/north-raleigh/",
    description: "Mobile pet grooming and at-home clipping for dogs and cats in the North Raleigh area. The groomer comes to your driveway.",
    city: "Raleigh",
    zip: "27614",
    neighborhoods: ["North Raleigh", "North Hills"],
    services: ["Full Groom", "Bath & Brush", "Cat Grooming"],
    rating: 4.9,
    review_count: 105,
  },
  {
    slug: "raleigh-lux-pup-grooming",
    business_name: "Lux Pup Grooming",
    phone: "(984) 298-0528",
    website: "https://www.luxpupgrooming.com/",
    description: "Raleigh's mobile pet salon offering full-service haircuts and baths & blowouts with dedicated one-on-one attention.",
    city: "Raleigh",
    zip: "27601",
    neighborhoods: ["Raleigh"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.4,
    review_count: 13,
  },
  {
    slug: "holly-springs-the-barkmobile",
    business_name: "The BarkMobile",
    phone: "(919) 500-6981",
    website: "https://www.oakcreekanimalcompany.com/",
    description: "Mobile dog grooming (Oak Creek Animal Company LLC) based at 624 Holly Springs Rd, specializing in nail grinding, baths, and full-service grooming for the Raleigh metro area including Apex, Cary, Morrisville, Fuquay-Varina, and Clayton.",
    city: "Holly Springs",
    zip: "27540",
    neighborhoods: ["Holly Springs", "Raleigh", "Apex", "Cary", "Morrisville", "Fuquay-Varina", "Clayton"],
    services: ["Full Groom", "Bath & Brush", "Nail Grinding"],
    rating: 3.7,
    review_count: 9,
  },
  {
    slug: "cary-woof-and-wheels",
    business_name: "Woof and Wheels Mobile Pet Salon",
    phone: "(919) 906-9663",
    website: "https://www.facebook.com/Woofandwheels/",
    description: "Mobile pet grooming based at 2501 Piney Plains Rd, Cary, providing less stress for pets and no mess for owners.",
    city: "Cary",
    zip: "27518",
    neighborhoods: ["Cary"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.3,
    review_count: 27,
  },
  {
    slug: "cary-bark-and-mane",
    business_name: "Bark & Mane of Cary and Pittsboro",
    phone: "(919) 589-7768",
    website: "https://www.aussiepetmobile.com/cary-apex-nc/",
    description: "Mobile dog and cat grooming (formerly Aussie Pet Mobile) bringing the spa experience directly to your doorstep in Cary, Pittsboro, and Apex.",
    city: "Cary",
    zip: "27519",
    neighborhoods: ["Cary", "Pittsboro", "Apex"],
    services: ["Full Groom", "Bath & Brush", "Cat Grooming"],
    rating: 4.9,
    review_count: 296,
  },
  {
    slug: "cary-pack-and-pride",
    business_name: "Pack & Pride",
    phone: "(919) 525-2120",
    website: "https://packandpride.com/mobile-dog-grooming/",
    description: "Mobile dog grooming booking clients in Raleigh, Cary, Apex, Holly Springs, Knightdale, Wake Forest, and Durham.",
    city: "Cary",
    zip: "27511",
    neighborhoods: ["Cary", "Raleigh", "Apex", "Holly Springs", "Knightdale", "Wake Forest", "Durham"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.9,
    review_count: 46,
  },
  {
    slug: "cary-groom-and-go-mobile-pet-salon",
    business_name: "Groom & Go Mobile Pet Salon",
    website: "https://www.groomandgomobile.com/",
    description: "Family-owned mobile pet grooming based at 702 Delmar Rd, Cary, NC, serving Cary, North Raleigh, Apex, and Morrisville.",
    city: "Cary",
    zip: "27511",
    neighborhoods: ["Cary", "Raleigh", "Apex", "Morrisville"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "apex-metrohound-mobile-pet-spa",
    business_name: "MetroHound Mobile Pet Spa",
    phone: "(919) 629-4290",
    website: "https://www.facebook.com/metrohoundspa/",
    description: "Stylish mobile grooming with one-on-one care in Apex, ideal for anxious or aging pets. Serves the Raleigh metro including Cary, Morrisville, Holly Springs, Garner, and Fuquay-Varina. The Better Business Bureau lists this business as believed to be out of business. Confirm availability before booking.",
    city: "Apex",
    zip: "27502",
    neighborhoods: ["Apex", "Cary", "Morrisville", "Holly Springs", "Garner", "Fuquay-Varina"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 3.8,
    review_count: 24,
  },
  {
    slug: "apex-dappertails",
    business_name: "DapperTails Mobile Pet Grooming",
    website: "https://www.dappertailsmobile.com/apex-nc",
    description: "Mobile pet grooming bringing the salon directly to your home in Apex, with baths, breed-specific haircuts, nail trims, and deshedding.",
    city: "Apex",
    zip: "27502",
    neighborhoods: ["Apex"],
    services: ["Full Groom", "Bath & Brush", "Nail Trim", "De-Shedding Treatment"],
  },
  {
    slug: "apex-wallywood-pet-spa",
    business_name: "WallyWood Pet Spa",
    phone: "(919) 980-2156",
    website: "https://www.wallywoodpetspa.com/",
    description: "Mobile and in-salon pet grooming based at 1126 Woodlands Creek Way, Apex, NC.",
    city: "Apex",
    zip: "27502",
    neighborhoods: ["Apex"],
    services: ["Full Groom", "Bath & Brush"],
    hours: "Mon-Sat 10:00am-10:00pm",
    rating: 4.6,
    review_count: 9,
  },
  {
    slug: "chapel-hill-clippendales",
    business_name: "Clippendales Mobile Pet Salon",
    phone: "(984) 369-4741",
    description: "Mobile pet grooming serving the Chapel Hill, NC area.",
    city: "Chapel Hill",
    zip: "27516",
    neighborhoods: ["Chapel Hill"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 2,
  },
  {
    slug: "chapel-hill-the-secret-groomer",
    business_name: "The Secret Groomer",
    website: "https://thesecretgroomer.com/",
    description: "Full-service mobile pet grooming serving the Raleigh, Durham, and Chapel Hill area (currently accepting existing clients only).",
    city: "Chapel Hill",
    zip: "27514",
    neighborhoods: ["Chapel Hill", "Raleigh", "Durham"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "garner-bark-and-bath",
    business_name: "Bark & Bath Mobile Groomers",
    description: "Mobile dog grooming based in Garner, NC.",
    city: "Garner",
    zip: "27529",
    neighborhoods: ["Garner"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "garner-grooming-at-tiffinys",
    business_name: "Grooming at Tiffinys",
    phone: "(702) 630-6141",
    description: "Cage-free mobile dog grooming based in Garner, NC.",
    city: "Garner",
    zip: "27529",
    neighborhoods: ["Garner"],
    services: ["Full Groom", "Bath & Brush"],
    hours: "Wed-Sun 10:00am-7:00pm (closed Mon-Tue)",
    rating: 3.0,
    review_count: 2,
  },
  {
    slug: "holly-springs-paws-fur-grooming",
    business_name: "Paws Fur Grooming",
    phone: "(910) 774-0355",
    website: "https://www.pawsfurgrooming.com/mobile-dog-grooming",
    description: "Mobile grooming serving the towns of Holly Springs, New Hill, Apex, and Fuquay-Varina.",
    city: "Holly Springs",
    zip: "27540",
    neighborhoods: ["Holly Springs", "New Hill", "Apex", "Fuquay-Varina"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.8,
    review_count: 459,
  },
  {
    slug: "zebulon-purrfect-paws-house-calls",
    business_name: "Purrfect Paws House Calls",
    phone: "(919) 763-6021",
    description: "Mobile pet care based in Zebulon specializing in in-home nail trim services.",
    city: "Zebulon",
    zip: "27597",
    neighborhoods: ["Zebulon"],
    services: ["Nail Trim"],
    rating: 4.0,
    review_count: 8,
  },
  {
    slug: "clayton-adorybull-groom-and-board",
    business_name: "Adorybull Groom & Board, LLC",
    phone: "(919) 359-1548",
    owner_name: "Francine Schrader",
    description: "Mobile pet grooming serving Clayton and surrounding communities throughout Johnston County, including Smithfield.",
    city: "Clayton",
    zip: "27520",
    neighborhoods: ["Clayton", "Smithfield"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.6,
    review_count: 96,
  },
  {
    slug: "clayton-cookie-mobile-grooming",
    business_name: "Cookie Mobile Grooming",
    phone: "(919) 520-6737",
    description: "Mobile dog grooming based in Clayton, NC.",
    city: "Clayton",
    zip: "27527",
    neighborhoods: ["Clayton"],
    services: ["Full Groom", "Bath & Brush"],
    hours: "Mon-Fri 8:30am-4:30pm",
    rating: 4.8,
    review_count: 59,
  },
  {
    slug: "clayton-fancy-pants-mobile-grooming",
    business_name: "Fancy Pants Mobile Grooming",
    phone: "(919) 495-4905",
    description: "Mobile dog grooming based in Clayton, NC.",
    city: "Clayton",
    zip: "27527",
    neighborhoods: ["Clayton"],
    services: ["Full Groom", "Bath & Brush"],
    hours: "Tue-Sat 9:00am-6:00pm",
    rating: 5.0,
    review_count: 4,
  },
  {
    slug: "greensboro-bark-and-mane",
    business_name: "Bark & Mane of Triad",
    website: "https://www.barkandmane.com/pet-groomers/triad-nc/",
    phone: "1-800-738-6624",
    description: "Mobile pet grooming servicing Greensboro and the surrounding Triad communities.",
    city: "Greensboro",
    zip: "27401",
    neighborhoods: ["Greensboro"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "greensboro-noahs-bark",
    business_name: "Noah's Bark Mobile Grooming",
    phone: "(336) 279-4459",
    description: "Mobile dog grooming based in Greensboro, NC.",
    city: "Greensboro",
    zip: "27410",
    neighborhoods: ["Greensboro"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.6,
    review_count: 45,
  },
  {
    slug: "greensboro-a-becoming-pet-salon",
    business_name: "A Becoming Pet Salon and Mobile Spa",
    phone: "(336) 834-3332",
    website: "https://abecomingpet.com/",
    description: "Award-winning grooming salon at 4609 W Market St, Greensboro, NC, also offering a mobile grooming unit.",
    city: "Greensboro",
    zip: "27407",
    neighborhoods: ["Greensboro"],
    services: ["Full Groom", "Bath & Brush"],
    hours: "Tue-Fri 7:30am-5:30pm (storefront hours; mobile hours vary)",
    rating: 4.5,
    review_count: 54,
  },
  {
    slug: "greensboro-bonejour-mobile-dog-grooming",
    business_name: "BoneJour Mobile Dog Grooming Salon",
    phone: "(336) 856-7895",
    website: "https://vivabonejour.com/",
    description: "Mobile dog grooming based in Greensboro, NC.",
    city: "Greensboro",
    zip: "27410",
    neighborhoods: ["Greensboro"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 2.5,
    review_count: 8,
    hours: "Wed 8:00am-4:00pm",
  },
  {
    slug: "greensboro-tickled-pink-pets-mobile-spa",
    business_name: "Tickled Pink Pets Mobile Spa",
    phone: "(336) 509-2704",
    description: "Mobile dog grooming based in Greensboro, NC.",
    city: "Greensboro",
    zip: "27410",
    neighborhoods: ["Greensboro"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.8,
    review_count: 27,
  },
  {
    slug: "thomasville-barkhaus-mobile-pet-spa",
    business_name: "Barkhaus Mobile Pet Spa",
    phone: "(336) 240-3410",
    website: "https://www.barkhauspetspa.com/",
    description: "Full-service, self-contained mobile grooming salon based at 540 Chase Rd, Thomasville, NC, also serving Greensboro and High Point.",
    city: "Thomasville",
    zip: "27360",
    neighborhoods: ["Thomasville", "Greensboro", "High Point"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.0,
    review_count: 8,
    hours: "Mon-Fri 8:30am-5:00pm, Sat 8:30am-12:00pm",
  },
  {
    slug: "thomasville-curbside-canine-cuts",
    business_name: "Curbside Canine Cuts",
    description: "One-on-one mobile dog grooming based at 640 Kanoy Rd, Thomasville, NC.",
    city: "Thomasville",
    zip: "27360",
    neighborhoods: ["Thomasville"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 1,
  },
  {
    slug: "thomasville-cutz-4-muttz-mobile-grooming",
    business_name: "Cutz 4 Muttz Mobile Grooming Spa",
    phone: "(979) 464-7941",
    description: "Mobile dog grooming based at 171 Kate Dr, Thomasville, NC.",
    city: "Thomasville",
    zip: "27360",
    neighborhoods: ["Thomasville"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 1.0,
    review_count: 1,
  },
  {
    slug: "high-point-royal-paws",
    business_name: "Royal Paws Pet Salon",
    phone: "(336) 307-4394",
    description: "Pet grooming salon located at 2531 Eastchester Dr, High Point, NC, offering mobile grooming options.",
    city: "High Point",
    zip: "27265",
    neighborhoods: ["High Point"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.5,
    review_count: 229,
  },
  {
    slug: "youngsville-classy-k9",
    business_name: "Classy K9 Mobile Grooming",
    phone: "(919) 637-9412",
    website: "https://www.classyk9mobilegrooming.com/",
    description: "Mobile dog grooming servicing Youngsville, Wake Forest, North Raleigh, North Durham, Rolesville, Franklinton, Creedmoor, and Henderson.",
    city: "Youngsville",
    zip: "27596",
    neighborhoods: ["Youngsville", "Wake Forest", "North Raleigh", "Rolesville", "Franklinton"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 106,
  },
  {
    slug: "angier-kr-groovin-grooming",
    business_name: "KR Groovin' Grooming LLC",
    phone: "(919) 396-2740",
    website: "https://www.facebook.com/KRGroovinGrooming/",
    description: "Local mobile dog grooming serving Harnett, Johnston, and Southern Wake County, including Angier.",
    city: "Angier",
    zip: "27501",
    neighborhoods: ["Angier"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 20,
  },
  {
    slug: "franklinton-mobile-grooming-by-heather",
    business_name: "Mobile Grooming by Heather LLC",
    website: "https://www.mobilegroomingbyheather.com/",
    phone: "(919) 642-1575",
    description: "Mobile pet grooming serving North Raleigh, Creedmoor, Wake Forest, Franklinton, Butner, and Stem.",
    city: "Franklinton",
    zip: "27525",
    neighborhoods: ["Franklinton", "North Raleigh", "Creedmoor", "Wake Forest", "Butner", "Stem"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.7,
    review_count: 15,
  },
  {
    slug: "butner-mobile-grooming-by-heather",
    business_name: "Mobile Grooming by Heather LLC",
    website: "https://www.mobilegroomingbyheather.com/",
    phone: "(919) 642-1575",
    description: "Mobile pet grooming serving Butner, North Raleigh, Creedmoor, Wake Forest, Franklinton, and Stem.",
    city: "Butner",
    zip: "27509",
    neighborhoods: ["Butner", "North Raleigh", "Creedmoor", "Wake Forest", "Franklinton"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.7,
    review_count: 15,
  },
  {
    slug: "youngsville-blissful-paws",
    business_name: "Blissful Paws Mobile Spaw",
    phone: "(919) 610-0058",
    description: "Mobile pet grooming based in Youngsville, serving Louisburg and Franklinton.",
    city: "Youngsville",
    zip: "27596",
    neighborhoods: ["Youngsville", "Louisburg", "Franklinton"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 5,
  },
  {
    slug: "morrisville-swifthounds-mobile",
    business_name: "Swifthounds Mobile",
    phone: "(919) 794-3799",
    description: "Mobile dog grooming based at 4101 Davis Dr, Morrisville, serving Carrboro, Chapel Hill, Pittsboro, and Durham.",
    city: "Morrisville",
    zip: "27560",
    neighborhoods: ["Morrisville", "Carrboro", "Chapel Hill", "Pittsboro", "Durham"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.9,
    review_count: 50,
  },
  {
    slug: "mebane-furry-land",
    business_name: "Furry Land Mobile Grooming",
    website: "https://furryland.us/pet-mobile-grooming-mebane-nc/",
    description: "Mobile pet grooming covering Mebane and surrounding neighborhoods.",
    city: "Mebane",
    zip: "27302",
    neighborhoods: ["Mebane"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "graham-puppy-love-n-style",
    business_name: "Puppy Love-N-Style",
    phone: "(336) 380-1615",
    description: "Pet grooming located at 917 E Harden St, Graham, NC, offering mobile grooming options.",
    city: "Graham",
    zip: "27253",
    neighborhoods: ["Graham"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.8,
    review_count: 133,
  },
  {
    slug: "graham-plum-pucci",
    business_name: "Plum Pucci",
    phone: "(336) 693-8600",
    description: "Pet grooming located at 127 E Elm St, Graham, NC, offering mobile grooming options.",
    city: "Graham",
    zip: "27253",
    neighborhoods: ["Graham"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.0,
    review_count: 63,
  },
  {
    slug: "selma-bath-and-biscuit",
    business_name: "Bath and Biscuit Mobile Pet Spa",
    description: "Mobile pet grooming based in Selma, NC, bringing grooming to your home or place of business.",
    city: "Selma",
    zip: "27576",
    neighborhoods: ["Selma"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "four-oaks-bubbles-and-bows",
    business_name: "Bubbles And Bows Mobile Grooming",
    phone: "(910) 514-4264",
    description: "Mobile dog grooming located at 209 E Wellons St, Four Oaks, NC (Johnston County).",
    city: "Four Oaks",
    zip: "27524",
    neighborhoods: ["Four Oaks"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 4.3,
    review_count: 16,
  },
  {
    slug: "jamestown-kallis-pet-spa",
    business_name: "Kallis Pet Spa LLC",
    website: "https://www.kallispetspa.com/",
    phone: "(336) 460-5569",
    description: "Luxury mobile pet care salon based in Randleman, NC, AKC Professional Groomer Certified and fully insured, serving Jamestown and the greater Triad region.",
    city: "Jamestown",
    zip: "27282",
    neighborhoods: ["Jamestown"],
    services: ["Full Groom", "Bath & Brush"],
    rating: 5.0,
    review_count: 37,
  },
  {
    slug: "smithfield-styles-by-sal",
    business_name: "Styles by Sal Mobile Dog Grooming",
    phone: "(702) 820-9180",
    description: "Mobile dog grooming serving Smithfield and surrounding areas, specializing in small dogs under 25 lbs.",
    city: "Smithfield",
    zip: "27577",
    neighborhoods: ["Smithfield"],
    rating: 5.0,
    review_count: 1,
    services: ["Bath & Brush", "Nail Trim", "Ear Cleaning", "Anal Gland Expression"],
    price_info: "Small dogs under 25 lbs: $65 flat (bath, brush, blow dry, nail clip & file, ears cleaned, anal glands expressed).",
  },
  {
    slug: "high-point-finns-feet-and-fannies",
    business_name: "Finn's Feet & Fannie's Mobile Dog Grooming",
    phone: "336-804-4481",
    website: "https://finnsfeetfanniesmobiledog.com/",
    description: "One-on-one mobile dog grooming in High Point, NC for dogs up to 80 lbs.",
    city: "High Point",
    zip: "27262",
    neighborhoods: ["High Point"],
    services: ["Full Groom", "Bath & Brush", "De-Shedding Treatment", "Anal Gland Expression", "De-Matting"],
    hours: "Open 8:30am-5:00pm",
    price_info:
      "Bath & Blowout $80-$120, Face/Feet/Fannie $90-$130, Full Groom $100-$140, Poodles & Doodles Full Groom $120-$160, add-ons (de-shed, anal gland expression, de-matting) $15 each.",
    rating: 5.0,
    review_count: 2,
  },
  {
    slug: "oxford-doggone-clean-mobile-pet-grooming",
    business_name: "Doggone Clean Mobile Pet Grooming",
    phone: "(919) 904-6512",
    description: "In-home mobile pet grooming covering Oxford and all of Granville County, NC.",
    city: "Oxford",
    zip: "27565",
    neighborhoods: ["Oxford"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "carrboro-furry-land-mobile-grooming",
    business_name: "Furry Land Mobile Grooming",
    phone: "(877) 726-3345",
    website: "https://furryland.us/pet-grooming-in-carrboro-nc-raleigh-durham/",
    description: "Mobile pet grooming serving Carrboro, NC and the greater Raleigh-Durham area.",
    city: "Carrboro",
    zip: "27510",
    neighborhoods: ["Carrboro"],
    services: ["Full Groom", "Bath & Brush"],
  },
  {
    slug: "hillsborough-furry-land-mobile-grooming",
    business_name: "Furry Land Mobile Grooming",
    phone: "(877) 726-3345",
    website: "https://furryland.us/pet-grooming-in-hillsborough-nc-raleigh-durham/",
    description: "Mobile pet grooming serving Hillsborough, NC and the greater Raleigh-Durham area.",
    city: "Hillsborough",
    zip: "27278",
    neighborhoods: ["Hillsborough"],
    services: ["Full Groom", "Bath & Brush"],
  },
];

async function run() {
  await ensureSchema();

  const existing = (await sql`SELECT COUNT(*)::int as c FROM groomers`) as unknown as { c: number }[];
  if (existing[0].c > 0) {
    console.log(`Database already has ${existing[0].c} rows. Skipping seed.`);
    return;
  }

  for (const g of groomers) {
    await sql`
      INSERT INTO groomers (
        slug, business_name, owner_name, email, phone, website, gmb_url, facebook_url,
        price_info, hours, description,
        city, zip, neighborhoods, services, service_radius_miles, years_experience,
        rating, review_count, featured, status, is_claimed
      ) VALUES (
        ${g.slug}, ${g.business_name}, ${g.owner_name ?? null}, ${null}, ${g.phone ?? null},
        ${g.website ?? null}, ${mapsSearchUrl(g.business_name, g.city)}, ${g.facebook_url ?? null},
        ${g.price_info ?? null}, ${g.hours ?? null}, ${g.description},
        ${g.city}, ${g.zip}, ${JSON.stringify(g.neighborhoods)}, ${JSON.stringify(g.services)},
        ${g.service_radius_miles ?? 15}, ${g.years_experience ?? null}, ${g.rating ?? 0}, ${g.review_count ?? 0}, 0, 'approved', 0
      )
    `;
  }

  const rated = groomers.filter((g) => (g.review_count ?? 0) > 0).length;
  console.log(`Seeded ${groomers.length} real groomers (${rated} with a confirmed rating, rest unrated/unclaimed).`);
}

run().then(() => process.exit(0));
